### ISSUE TITLE
Unmet peer rollup@^ 2.61.1  when using pnpm to install package

### ISSUE THREAD

**Issue by tuanphamcybozu** [koba04/rollup-plugin-ecma-version-validator#38]
## User story

```
As a <user of rollup-plugin-ecma-version-validator library>,
I want <to update `rollup` package to newest version>
so that <I can finish the migrating from yarn to pnpm in my project (kintone/js-sdk)>
```

## Acceptance Criteria

1. Update `rollup` to newest version (3.26.3)
https://www.npmjs.com/package/rollup?activeTab=versions

## Background
When running `pnpm install` in js-sdk project, I got this error:
```
WARN  Issues with peer dependencies found
packages/rest-api-client
├─┬ rollup-plugin-ecma-version-validator 0.2.12
│ └── ✕ unmet peer rollup@^2.16.1: found 3.26.3
└─┬ rollup-plugin-terser 7.0.2
  └── ✕ unmet peer rollup@^2.0.0: found 3.26.3
```
And I think it is caused by the old version of `rollup` package.
Ref: https://github.com/koba04/rollup-plugin-ecma-version-validator/blob/master/package.json#L38

**Comment by tuanphamcybozu** [comment]
I resolved this problem in my project. So I close this issue.
Sorry for bothering.

**Comment by hung-cybo** [comment]
@koba04 san

Thank you for your great package.

Currently, I also face this issue.
So, I created a new PR to add rollup 3x to `peerDependencies` of this package.
Could you help to check it?
Thank you so much
